<a href="https://colab.research.google.com/github/romanzes637/algebra/blob/master/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural numbers $\mathbb{N}$

0, 1, 2, ...

or without 0

1, 2, 3, ...

1-tuple (1) of $\mathbb{N}$, e.g. (1), (4) or (100) 

Addition table

|  | 1 |
| :-: | :-: | 
| 1 | 1 |

Multiplication table

|  | 1 |
| :-: | :-: | 
| 1 | 1 |

# Integers $\mathbb{Z}$

..., -2, -1, 0, 1, 2, ...

or without 0

..., -2, -1, 1, 2, ...

2-tuple (1, -1) of $\mathbb{N}$, e.g. (1, 10), (4, 5) or (1000, 100)

1 - positive part

-1 - negative part

Addition table

| | 1 | -1|
| :-: | :-: | :-: |
| 1 | 1 |  |
| -1 |  | -1 |

Subtraction table

| | 1 | -1|
| :-: | :-: | :-: |
| 1 |  | 1 |
| -1 | -1 |  |

Multiplication table (equal to XNOR gate)

| | 1 | -1|
| :-: | :-: | :-: |
| 1 | 1 | -1 |
| -1 | -1 | 1 |

Division table (it's not a simple task)

with powerset extension (see below)

|  | 1 | -1 | 1 -1 | 
| :-: | :-: | :-: | :-: |
| 1 | \| \| \| \| | \| \| \| \| | \| \| \| \| |
| -1 | \| \| \| \| | \| \| \| \| | \| \| \| \| |
| 1 -1 | \| \| \| \| | \| \| \| \| | \| \| \| 1 -1 \| | |

Negation (NOT gate)

| | |
| :-: | :-: |
| 1 | -1 | 
| -1 | 1 |

# Rational numbers $\mathbb{Q}$

..., -2, -1, -1/2, -1/3, ..., 0, ..., 1/3, 1/2, 1, 2, ...

or without 0

..., -2, -1, -1/2, -1/3, ..., 1/3, 1/2, 1, 2, ...

2-tuple (1/, -1/) of positive $\mathbb{Q}$

Addition table

| | 1/ | -1/|
| :-: | :-: | :-: |
| 1/ | 1/ |  |
| -1/ |  | -1/ |

Multiplication table (equal to XNOR gate)

| | 1/ | -1/|
| :-: | :-: | :-: |
| 1/ | 1/ | -1/ |
| -1/ | -1/ | 1/ |

# Real numbers $\mathbb{R}$

..., -4, -$\pi$, -3, -$e$, -$\sqrt{5}$, -2,  -$\sqrt{3}$, -$\phi$, -$\sqrt{2}$,  -1, -0.1, -0.01, ..., 0, ..., 0.01, 0.1, 1, $\sqrt{2}$, $\phi$, $\sqrt{3}$, 2, $\sqrt{5}$, $e$, 3, $\pi$, 4 ...

or without 0

..., -4, -$\pi$, -3, -$e$, -$\sqrt{5}$, -2,  -$\sqrt{3}$, -$\phi$, -$\sqrt{2}$,  -1, -0.1, -0.01, ..., 0.01, 0.1, 1, $\sqrt{2}$, $\phi$, $\sqrt{3}$, 2, $\sqrt{5}$, $e$, 3, $\pi$, 4 ...

2-tuple (1., -1.) of positive $\mathbb{R}$

Addition table

| | 1. | -1.|
| :-: | :-: | :-: |
| 1. | 1. |  |
| -1. |  | -1. |

Multiplication table (equal to XNOR gate)

| | 1. | -1.|
| :-: | :- :| :-: |
| 1. | 1. | -1. |
| -1. | -1. | 1. |

# Complex numbers $\mathbb{C}$

4-tuple (1., -1., i, -i) of positive $\mathbb{R}$

Addition table

| | 1. | -1.| i | -i |
| :-: | :-: | :-: | :-: | :-: |
| 1. | 1. |  |  |  |
| -1. |  | -1. |  |  |
| i |  |  | i |  |
| -i |  |  |  | -i |

Multiplication table (plain - XNOR gate, **bold** - XOR gate)

| | 1. | -1.| i | -i |
| :-: | :-: | :-: | :-: | :-: |
| 1. | 1. | -1. | i | -i |
| -1. | -1. | 1. | -i | i |
| i | i | -i | **-1.**  | **1.** |
| -i | -i | i | **1.** | **-1.** |

# Quaternions $\mathbb{H}$

8-tuple (1., -1., i, -i, j, -j, k, -k) of positive $\mathbb{R}$

Addition table

| | 1. | -1.| i | -i | j | -j | k | -k |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1. | 1. |  |  |  |  |  |  |  |
| -1. |  | -1. |  |  |  |  |  |  |
| i |  |  | i |  |  |  |  |  |
| -i |  |  |  | -i |  |  |  |  |
| j |  |  |  |  | j |  |  |  |
| -j |  |  |  |  |  | -j |  |  |
| k |  |  |  |  |  |  | k |  |
| -k |  |  |  |  |  |  |  | -k |

Multiplication table (plain - XNOR gate, **bold** - XOR gate)

| | 1. | -1.| i | -i | j | -j | k | -k |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1. | 1. | -1. | i | -i | j | -j | k | -k |
| -1. | -1. | 1. | -i | i | -j | j | -k | k |
| i | i | -i | **-1** | **1** | k | -k | **-j** | **j** |
| -i | -i | i | **1** | **-1** | -k | k | **j** | **-j** |
| j | j | -j | **-k** | **k** | **-1** | **1** | i | -i |
| -j | -j | j | **k** | **-k** | **1** | **-1** | -i | i |
| k | k | -k | j | -j | **-i** | **i** | **-1** | **1** |
| -k | -k | k | -j | j | **i** | **-i** | **1** | **-1** |

# Octonions $\mathbb{O}$

16-tuple (1., -1., i, -i, j, -j, k, -k, m, -m, n, -n, p, -p, q, -q) of positive $\mathbb{R}$

Addition table

|  | 1. | -1.| i | -i | j | -j | k | -k | m | -m | n | -n | p | -p | q | -q |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1. | 1. |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| -1. |  | -1. |  |  |  |  |  |  |  |  |  |  |  |  |  |  |   
| i |  |  | i |  |  |  |  |  |  |  |  |  |  |  |  |  |
| -i |  |  |  | -i |  |  |  |  |  |  |  |  |  |  |  |  | 
| j |  |  |  |  | j |  |  |  |  |  |  |  |  |  |  |  |
| -j |  |  |  |  |  | -j |  |  |  |  |  |  |  |  |  |  | 
| k |  |  |  |  |  |  | k |  |  |  |  |  |  |  |  |  | 
| -k |  |  |  |  |  |  |  | -k |  |  |  |  |  |  |  |  |
| m |  |  |  |  |  |  |  |  | m |  |  |  |  |  |  |  |
| -m |  |  |  |  |  |  |  |  |  | -m |  |  |  |  |  |  |
| n |  |  |  |  |  |  |  |  |  |  | n |  |  |  |  |  |
| -n |  |  |  |  |  |  |  |  |  |  |  | -n |  |  |  |  |
| p |  |  |  |  |  |  |  |  |  |  |  |  | p |  |  |  |
| -p |  |  |  |  |  |  |  |  |  |  |  |  |  | -p |  |  |
| q |  |  |  |  |  |  |  |  |  |  |  |  |  |  | q |  |
| -q |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | -q |

Multiplication table (plain - XNOR gate, **bold** - XOR gate)

|  | 1. | -1.| i | -i | j | -j | k | -k | m | -m | n | -n | p | -p | q | -q |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1. | 1. | -1. | i | -i | j | -j | k | -k | m | -m | n | -n | p | -p | q | -q |
| -1. | -1. | 1. | -i | i | -j | j | -k | k | -m | m | -n | n | -p | p | -q | q |   
| i | i | -i | **-1.** | **1.** | k | -k | **-j** | **j** | n | -n | **-m** | **m** | **-q** | **q** | p | -p |
| -i | -i | i | **1.** | **-1.** | -k | k | **j** | **-j** | -n | n | **m** | **-m** | **q** | **-q** | -p | p | 
| j | j | -j | **-k** | **k** | **-1** | **1** | i | -i | p | -p | q | -q | **-m** | **m** | **-n** | **n** |
| -j | -j | j | **k** | **-k** | **1** | **-1** | -i | i | -p | p | -q | q | **m** | **-m** | **n** | **-n** | 
| k | k | -k | j | -j | **-i** | **i** | **-1.** | **1.** | q | -q | **-p** | **p** | n | -n | **-m** | **m** | 
| -k | -k | k | -j | j | **i** | **-i** | **1.** | **-1.** | -q | q | **p** | **-p** | -n | n | **m** | **-m** |
| m | m | -m | **-n** | **n** | **-p** | **p** | **-q** | **q** | **-1.** | **1.** | i | -i | j | -j | k | -k |
| -m | -m | m | **n** | **-n** | **p** | **-p** | **q** | **-q** | **1.** | **-1.** | -i | i | -j | j | -k | k |
| n | n | -n | m | -m | **-q** | **q** | p | -p | **-i** | **i** | **-1.** | **1.** | **-k** | **k** | j | -j |
| -n | -n | n | -m | m | **q** | **-q** | -p | p | **i** | **-i** | **1.** | **-1.** | **k** | **-k** | -j | j |
| p | p | -p | q | -q | m | -m | **-n** | **n** | **-j** | **j** | k | -k | **-1.** | **1.** | **-i** | **i** |
| -p | -p | p | -q | q | -m | m | **n** | **-n** | **j** | **-j** | -k | k | **1.** | **-1.** | **i** | **-i** |
| q | q | -q | **-p** | **p** | n | -n | m | -m | **-k** | **k** | **-j** | **j** | i | -i | **-1.** | **1.** |
| -q | -q | q | **p** | **-p** | -n | n | -m | m | **k** | **-k** | **j** | **-j** | -i | i | **1.** | **-1.** |

# Natural numbers null extension $\mathbb{N}$

0, 1, 2, ...

or without 0

1, 2, 3, ...

2-tuple (1, 0) of $\mathbb{N}$, e.g. (1, 2), (4, 5) or (100, 12) 

Addition table

|  | 1 | 0 |
| :-: | :-: | :-: |
| 1 | 1 | 0 |
| 0 | 0 | 0 |

Multiplication table

|  | 1 | 0 |
| :-: | :-: | :-: |
| 1 | 1 | 0 |
| 0 | 0 | 0 |

# Table's extension by powerset 

with null $\varnothing$

3D table 

$2^n\times2^n\times2^n$

$2^{3n}$ relations (functions) from (row, column) to depth, e.g. f(1, 0) to 1, or f(1 0, 0) to $\varnothing$ (trivial)

|  | 1 | 0 | 1 0 | $\varnothing$ | 
| :-: | :-: | :-: | :-: | :-: |
| 1 | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| |
| 0 | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| |
| 1 0 | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| |
| $\varnothing$ | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | \| 1 \| 0 \| 1 0 \| $\varnothing$ \| | |

without null $\varnothing$

3D table 

$(2^n-1)\times(2^n-1)\times(2^n-1)$

$(2^n-1)^3$ relations (functions)

|  | 1 | 0 | 1 0 |
| :-: | :-: | :-: | :-: |
| 1 | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| |
| 0 | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| |
| 1 0 | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| | \| 1 \| 0 \| 1 0 \| | |

## Table's extension by powerset with various dimensions and number inputs and outputs

n - input dimension

m - output dimension

p - number of inputs

q - number of outputs

# with null $\varnothing$

$\text(p + q)D$ table

$\underbrace{2^n\times{\ldots}\times2^n}_{p-times}\times \underbrace{2^m\times{\ldots}\times2^m}_{q-times}$

or

$\text(p + 1)D$ table

$\underbrace{2^n\times{\ldots}\times2^n}_{p-times}\times 2^{qm}$

or

$\text(1 + q)D$ table

$ 2^{pm}\times\underbrace{2^m\times{\ldots}\times2^m}_{q-times}$

or

$\text2D$ table

$2^{pn}\times 2^{qm}$

relations (functions)

$2^{pn}2^{qm}=2^{pn+qm}$

# without null $\varnothing$

$\left({p + q}\right)D$ table 

$ \underbrace{(2^n-1)\times{\ldots}\times(2^n-1)}_{p-times}\times \underbrace{(2^m-1)\times{\ldots}\times(2^m-1)}_{q-times}$

relations (functions)

$(2^n-1)^p(2^m-1)^q$

In [0]:
import math
n = 3  # input dim, e.g. RGB space (R, G, B)
m = 3  # output dim, e.g. RGB space (R, G, B)
p = 3  # n inputs, e.g. red (1, 0, 0), green (0, 1, 0) and blue (0, 0, 1) colors    
q = 2  # n outputs, arbitrary two colors: (R1, G1, B1) and (R2, G2, B2)
print('dim in: {}\ndim out: {}\nn in: {}\nn out: {}'.format(m, n, p, q))
print('with null')
i = 2**(p*n)
o = 2**(q*m)
f = 2**(p*n + q*m)
print('table (' + ' x '.join(['{}'.format(2**n) for _ in range(p)]) 
      + ') x (' + ' x '.join(['{}'.format(2**m) for _ in range(q)]) + ')')
print('function input types: {}'.format(i))
print('function output types: {}'.format(o))
print('types of functions: {}'.format(f))
print('without null')
i = (2**n - 1)**p
o = (2**m - 1)**q
f = (2**n - 1)**p*(2**m - 1)**q
print('table (' + ' x '.join(['{}'.format(2**n - 1) for _ in range(p)]) 
       + ') x (' + ' x '.join(['{}'.format(2**m - 1) for _ in range(q)]) + ')')
print('function input types: {}'.format(i))
print('function output types: {}'.format(o))
print('types of functions: {}'.format(f))

dim in: 3
dim out: 3
n in: 3
n out: 2
with null
table (8 x 8 x 8) x (8 x 8)
function input types: 512
function output types: 64
types of functions: 32768
without null
table (7 x 7 x 7) x (7 x 7)
function input types: 343
function output types: 49
types of functions: 16807


1.  signal
2.  sequence od signals
3.  numbers concepts
4.  numbers features
5.  numbers
6.  operations concepts
7.  operations features
8.  operations

numbers concepts:
1.   positivness/negativness
2.   wholeness/partiality

$number\ of\ features = 2^{number\ of\ concepts}$

1 concept featurs = (pos, neg)

2 concept features = (whole, part)

1 and 2 concept features = (pos whole, pos part, neg whole, neg part)



# operators concepts
number of functions

n - input dimension

m - output dimension

p - number of inputs

q - number of outputs

$2^{pn}2^{qm}=2^{pn+qm}$

$2^{2\cdot 4+1\cdot 4} = 2^{12}= 4096$



unary
1.   invertibility

## 1 or 2 concept

$\begin{matrix}
0 & 1\\
1 & 0\\
\end{matrix}$

## 1 and 2 concepts

### pos/neg

$\begin{matrix}
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 0 & 1\\
\end{matrix}$

or

$\begin{matrix}
1 & 0 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
\end{matrix}$

### whole/part 

$\begin{matrix}
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0\\
\end{matrix}$

## pos/neg and whole/part

$\begin{matrix}
0 & 0 & 0 & 1\\
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
\end{matrix}$

or

$\begin{matrix}
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1\\
1 & 0 & 0 & 0\\
\end{matrix}$


binary

1.  combination
2.  replacement

1 concept combination

$(p1 + p2,\ n1 + n2)$

2 concept combination

$(w1\cdot p2 + w2\cdot p1,\ p1\cdot p2)$

1 concept replacement

$(p1\cdot p2 + n1\cdot n2,\ p1\cdot n2 + n1\cdot p2)$


2 concept replacement

$(w1\cdot w2,\ p1\cdot p2)$

## 1 and 2 concept

$ (pw,\ pp,\ nw,\ np)$ - number

$pw$ - postitve whole

$pp$ - positive part

$nw$ - negative whole

$np$ - negative part

1 and 2 concept combination

$(\\
  pw1\cdot pp2 + pp1\cdot pw2 + nw1\cdot np2 + np1\cdot nw2,\\
  pp1\cdot pp2 + np1\cdot np2,\\
  pw1\cdot np2 + pp1\cdot nw2 + nw1\cdot pp2 + np1\cdot pw2,\\
  pp1\cdot np2 + np1\cdot pp2\\
  )$

1 and 2 concept replacement

$(\\
  pw1\cdot pw2 + nw1\cdot nw2,\\
  pp1\cdot pp2 + np1\cdot np2,\\
  pw1\cdot nw2 + nw1\cdot pw2,\\
  pp1\cdot np2 + np1\cdot pp2\\
  )$


# Combination

$\begin{bmatrix}
0 & 1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\
\end{bmatrix}
\cdot
\begin{bmatrix}
pw1\cdot pw2\\
pw1\cdot pp2\\
pw1\cdot nw2\\
pw1\cdot np2\\
pp1\cdot pw2\\
pp1\cdot pp2\\
pp1\cdot nw2\\
pp1\cdot np2\\
nw1\cdot pw2\\
nw1\cdot pp2\\
nw1\cdot nw2\\
nw1\cdot np2\\
np1\cdot pw2\\
np1\cdot pp2\\
np1\cdot nw2\\
np1\cdot np2\\
\end{bmatrix}
=
\begin{bmatrix}
pw3\\
pp3\\
nw3\\
np3\\
\end{bmatrix}$

# Replacement

$\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\
\end{bmatrix}
\cdot
\begin{bmatrix}
pw1\cdot pw2\\
pw1\cdot pp2\\
pw1\cdot nw2\\
pw1\cdot np2\\
pp1\cdot pw2\\
pp1\cdot pp2\\
pp1\cdot nw2\\
pp1\cdot np2\\
nw1\cdot pw2\\
nw1\cdot pp2\\
nw1\cdot nw2\\
nw1\cdot np2\\
np1\cdot pw2\\
np1\cdot pp2\\
np1\cdot nw2\\
np1\cdot np2\\
\end{bmatrix}
=
\begin{bmatrix}
pw3\\
pp3\\
nw3\\
np3\\
\end{bmatrix}$

In [6]:
import numpy as np

def to_h(v):
  return (v[0]-v[2])/(v[1]-v[3])

wc = np.array([
  [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
wci = np.array([
  [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
wr = np.array([
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
wri = np.array([
  [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
wn = np.array([
  [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
wni = np.array([
  [0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
  ])
a = [8, 5, 3, 2]
b = [6, 9, 12, 3]
# a = [1, 4, 7, 1]
# b = [5, 1, 3, 3]
ah = to_h(a)
bh = to_h(b)
print(ah, bh)
ab = np.array([
  a[0]*b[0], a[0]*b[1], a[0]*b[2], a[0]*b[3], 
  a[1]*b[0], a[1]*b[1], a[1]*b[2], a[1]*b[3],
  a[2]*b[0], a[2]*b[1], a[2]*b[2], a[2]*b[3],
  a[3]*b[0], a[3]*b[1], a[3]*b[2], a[3]*b[3]
  ])
c = wc.dot(ab)
r = wr.dot(ab)
n = wn.dot(ab)
ri = wri.dot(ab)
ci = wci.dot(ab)
ni = wni.dot(ab)
print(c, r, n)
print(ci, ri, ni)
ch = to_h(c)
rh = to_h(r)
nh = to_h(n)
rih = to_h(ri)
cih = to_h(ci)
nih = to_h(ni) 
print(ah+bh, ah*bh, ah*bh+ah+bh)
print(ch, rh, nh)
print(cih, rih, nih)

1.6666666666666667 -1.0
[135  51 123  33] [ 84  51 114  33] [219  51 237  33]
[123  51 135  33] [114  51  84  33] [237  51 219  33]
0.6666666666666667 -1.6666666666666667 -1.0
0.6666666666666666 -1.6666666666666667 -1.0
-0.6666666666666666 1.6666666666666667 1.0
1.6666666666666667 -1.0
[135  51 123  33] [ 84  51 114  33] [219  51 237  33]
[123  51 135  33] [114  51  84  33] [237  51 219  33]
0.6666666666666667 -1.6666666666666667 -1.0
0.6666666666666666 -1.6666666666666667 -1.0
-0.6666666666666666 1.6666666666666667 1.0
